import { Inter, Roboto_Mono } from "next/font/google";
import { ReactNode } from "react";
import "./globals.css";
import { DarkMode } from "@/context/darkModeContext";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

const robotoMono = Roboto_Mono({ subsets: ["latin"], variable: "--font-mono" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${robotoMono.variable} overflow-hidden font-body text-gray-50`}
      >
        <DarkMode>{children}</DarkMode>
      </body>
    </html>
  );
}
